# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Docs CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Mudkip
        run: |
          curl -o mudkip.tgz -L https://github.com/barelyhuman/mudkip/releases/latest/download/linux-amd64.tgz
          tar -xvzf mudkip.tgz
          install linux-amd64/mudkip /usr/local/bin
      - name: Build
        run: |
          mudkip --baseurl="/thestack/" -o='docs_dist' --stylesheet='docs/styles.css'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './docs_dist'

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
